version: '3'
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frontend_practice
    ports:
      - "5432:5432"
